model:
  base_learning_rate: 4.5e-06
  target: taming.models.vqgan.VQModel
  params:
    embed_dim: 256
    n_embed: 16384
    ddconfig:
      double_z: false
      z_channels: 256
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 1
      - 2
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions:
      - 16
      dropout: 0.0
    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: false
        disc_in_channels: 3
        disc_start: 150000
        disc_weight: 0.8
        codebook_weight: 1.0
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 2
    num_workers: 8
    train:
      target: taming.data.wikiart.WikiArtTrain
      params:
        size: 256
        augmentations:
          rescale: 1.2
          crop: random
          hflip: true
          vflip: true
          bright_contrast:
            p: 0.2
            limit: [-0.1, 0.1]
    validation:
      target: taming.data.wikiart.WikiArtValidation
      params:
        size: 256
lightning:
  trainer:
    accumulate_grad_batches: 6
    log_every_n_steps: 50
    precision: 16